### ISSUE TITLE
Empty phone number is not getting validated.

### ISSUE THREAD

**Issue by Dileepadari** [Clubs-Council-IIITH/users#7]
When the user remove the phone number and submit the form , The validation of user is not happening due to an error in validation of phone number further redirecting to 404.

**Comment by bhavberi** [comment]
Hi,

This issue is fixed in the commit https://github.com/Clubs-Council-IIITH/users/commit/0a4c48a6991ff0c1c03dd231fa866b020aaba108. 
Closing.
